ds.field_plugin.image_attributes_field.*:
  type: mapping
  label: 'Mapping for the image_attributes_field field settings'
  mapping:
    responsive_image_style:
      type: string
      label: 'Responsive image style'

ds.field_plugin.media_image_attributes_field.*:
  type: mapping
  label: 'Mapping for the media_image_attributes_field field settings'
  mapping:
    responsive_image_style:
      type: string
      label: 'Responsive image style'