#!/bin/bash

# Go to base level of project
cd "$(dirname $0)/../../"

if [ -z "$TERMINUS_SITE" ] || [ -z "$TERMINUS_ENV" ]
then
  echo 'No test site specified. Set TERMINUS_SITE and TERMINUS_ENV.'
  exit 1
fi

echo ":::::::::::::::::::::::::::::::::::::::::::::::::"
echo "Running Backstop tests against: $TERMINUS_ENV-$TERMINUS_SITE"
echo ":::::::::::::::::::::::::::::::::::::::::::::::::"
cd ../web/themes/x
/usr/bin/nodejs  --harmony ./node_modules/backstopjs/cli/index.js test --config=backstop.config.js --filter=hero-standard --env=$TERMINUS_ENV-$TERMINUS_SITE.pantheonsite.io/themes/x/dist/public