#!/bin/bash

# We need to do some additional work for Visual regression testing, so
# these extra packages are added.

# Go to base level of project
cd "$(dirname $0)/../../"

echo "::::::::::::::::::::::::::::::::::::::::::::::::"
echo "Saving Backstop data"
echo "::::::::::::::::::::::::::::::::::::::::::::::::"

mkdir -p /tmp/artifacts
tar -zcvf backstop_data.tar.gz --directory=../web/themes/x backstop_data
mv backstop_data.tar.gz /tmp/artifacts
