#!/bin/bash

set -eo pipefail

# Avoid ssh prompting when connecting to new ssh hosts
mkdir -p $HOME/.ssh && echo "StrictHostKeyChecking no" >> "$HOME/.ssh/config"

# Configure the GitHub Oauth token if it is available
if [ -n "$GITHUB_TOKEN" ] ; then
  composer -n config --global github-oauth.github.com $GITHUB_TOKEN
fi

# Set up our default git config settings.
git config --global user.email "$GIT_EMAIL"
git config --global user.name "Circle CI"
git config --global core.fileMode false

# This is a forked file based on https://github.com/pantheon-systems/docker-build-tools-ci/blob/1.x/scripts/set-environment
# which is the file Pantheon uses by default to set environment variables

# Set up environment variables

# By default, we will make the environment name after the circle build number.
# DEFAULT_ENV=ci-$CIRCLE_BUILD_NUM

# If there is a PR number provided, though, then we will use it instead.
# if [[ -n ${CIRCLE_PULL_REQUEST} ]] ; then
  # PR_NUMBER=${CIRCLE_PULL_REQUEST##*/}
  # DEFAULT_ENV="pr-${PR_NUMBER}"
# fi


# By default, use the name of the git feature branch (e.g. jul-18)
# If it is a merge and we are on the master branch,
# get the name of the merged branch and use that one. 

DEFAULT_ENV="${CIRCLE_BRANCH}-test"
IRC_MONTHLY_ENV=$CIRCLE_BRANCH

#GIT_COMMIT_MESSAGE="$(git log --format=%s -n 1 $CIRCLE_SHA1)"

#if [[ $GIT_COMMIT_MESSAGE = *"Merge pull request"* ]]; then
#	BRANCH=${GIT_COMMIT_MESSAGE#*/}
#	DEFAULT_ENV="${BRANCH}"
#fi


#=====================================================================================================================
# EXPORT needed environment variables
#
# Circle CI 2.0 does not yet expand environment variables so they have to be manually EXPORTed
# Once environment variables can be expanded this section can be removed
# See: https://discuss.circleci.com/t/unclear-how-to-work-with-user-variables-circleci-provided-env-variables/12810/11
# See: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
# See: https://discuss.circleci.com/t/circle-2-0-global-environment-variables/8681
#=====================================================================================================================
(
  echo 'export PATH=$PATH:$HOME/bin'
  echo "export DEFAULT_ENV='$DEFAULT_ENV'"
  echo 'export TERMINUS_HIDE_UPDATE_MESSAGE=1'
  echo 'export TERMINUS_ENV=${TERMINUS_ENV:-$DEFAULT_ENV}'
  echo "export IRC_MONTHLY_ENV='$IRC_MONTHLY_ENV'"
) >> $BASH_ENV
source $BASH_ENV

# Re-install the Terminus Build Tools plugin if requested
if [ -n $BUILD_TOOLS_VERSION ] && [ "$BUILD_TOOLS_VERSION" <> 'dev-master' ]; then
  echo "Install Terminus Build Tools Plugin version $BUILD_TOOLS_VERSION"
  rm -rf ${TERMINUS_PLUGINS_DIR:-~/.terminus/plugins}/terminus-build-tools-plugin
  composer -n create-project -d ${TERMINUS_PLUGINS_DIR:-~/.terminus/plugins} pantheon-systems/terminus-build-tools-plugin:$BUILD_TOOLS_VERSION
fi