name: rescue-x
recipe: pantheon
config:
  framework: drupal8
  site: rescue-x
  id: c8430b75-4272-4aca-bfcd-206b12279315
  webroot: web
services:
  appserver:
    xdebug: true
    run:
      - "cd $LANDO_MOUNT && composer install"
    overrides:
      services:
        environment:
          PHP_IDE_CONFIG: "serverName=appserver"
  database:
       portforward: 3308
tooling:
  drush:
    cmd: /app/vendor/bin/drush
  gulp:
    service: appserver
  drupal:
    service: appserver
    cmd:
      - "/app/vendor/bin/drupal"
      - "--root=/app/web"