name: rescue-x
recipe: pantheon
config:
  framework: drupal8
  site: rescue-x
  id: c8430b75-4272-4aca-bfcd-206b12279315
services:
  database:
    portforward: 3308
  appserver:
    xdebug: true
    run:
      - "cd $LANDO_MOUNT && composer install"
    overrides:
      services:
        # Latest version of node and other dependencies.
        # See: https://hub.docker.com/r/ircdigital/irc-lando-build
        # Image is based on https://hub.docker.com/r/devwithlando/pantheon-appserver
        image: ircdigital/irc-lando-build:7.2-2
        environment:
          PHP_IDE_CONFIG: "serverName=appserver"
tooling:
  gulp:
    service: appserver
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
      - "--root=/app/web"
proxy:
  appserver:
    - rpl.rescuex.lndo.site:3000