name: rescue-x
recipe: pantheon
config:
  framework: drupal8
  site: rescue-x
  id: c8430b75-4272-4aca-bfcd-206b12279315
services:
  database:
    portforward: 3307
  appserver:
    xdebug: true
    overrides:
      services:
        # Latest version of node and other puppeteer dependencies
        # are included in this Docker container
        image: ircdigital/irc-lando-build
        environment:
          PHP_IDE_CONFIG: "serverName=appserver"
    # Install project dependencies:
    # - Drupal core
    run_as_root:
      - "composer install -d /app"
    # - "npm install -g gulp-cli -y"
    # - "npm install /app/web/themes/x"
tooling:
  gulp:
    service: appserver
proxy:
  appserver:
    - rpl.rescuex.lndo.site:3000