<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityDisplayInterface;


/**
 * Implements hook_entity_view_alter().
 */
function ef_curated_content_wrapper_entity_view_alter(&$build, EntityInterface $entity, EntityDisplayInterface $display) {

  if ($entity->getEntityType()->id() == 'reach_through' && $entity->bundle() == 'curated_content_wrapper') {
    /** @var \Drupal\node\NodeInterface $node */
    $node = $entity->reach_through_ref->entity;

    $build["field_ccw_slug"][0]["#context"]["value"] = 'Blah';
    //$render_array = $node->field_slug->view('teaser');
    //$build["field_ccw_slug"] = $render_array;
  }
}