<?php

use Drupal\ef\EmbeddableConfigurationHelper;

function ef_is_widescreen_install () {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(EmbeddableConfigurationHelper::class)
    ->addCropToMediaImageForm('widescreen_16x9');
}

function ef_is_widescreen_uninstall () {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(EmbeddableConfigurationHelper::class)
    ->removeCropFromMediaImageForm('widescreen_16x9');
}