<?php

use Drupal\ef_efficiency_graphic\EfficiencyGraphicThemeHelper;

/**
 * Implements hook_theme
 *
 * @return array
 */
function ef_efficiency_graphic_theme() {

  return [
    'ef_efficiency_graphic' => [
      'variables' => [],
    ]
  ];
}

function template_preprocess_ef_efficiency_graphic (&$variables) {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(EfficiencyGraphicThemeHelper::class)
    ->preprocessEfficiencyGraphic($variables);
}
