<?php

use Drupal\ef_social_menu\SocialThemeHelper;


/**
 * Implements hook_theme
 *
 * @return array
 */
function ef_social_menu_theme() {

  return [
    'ef_social_follow' => [
      'variables' => [],
    ],
  ];
}

function template_preprocess_ef_social_follow (&$variables) {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(SocialThemeHelper::class)
    ->preprocessSocialFollow($variables);
}