<?php

/**
 * Implements hook_theme().
 */
function ef_lead_generation_form_theme($existing, $type, $theme, $path) {
  return [
    'webform__simple_help_sign_up_form' => [
      'base hook' => 'webform',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ef_lead_generation_form_preprocess_webform__simple_help_sign_up_form (&$variables) {
  $variables['simple_help_sign_up_form'] = [
    '#type' => "pattern",
    '#id' => 'button',
    '#fields' => [
      'button_text' => 'hello',
      'button_url' => '/',
    ],
  ];
}