<?php

/**
 * Implements hook_theme().
 */
function ef_lead_generation_form_theme($existing, $type, $theme, $path) {
  return [
    'webform__simple_help_sign_up_form' => [
      'base hook' => 'webform',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ef_lead_generation_form_preprocess_webform__simple_help_sign_up_form (&$variables) {
  $variables['simple_help_sign_up_form'] = [
    '#type' => "pattern",
    '#id' => 'simple_email_sign_up',
    '#fields' => [
      'email_signup_title' => 'Join our mailing list',
      'email_signup_form_action' => '/',
      'email_signup_form_method' => 'GET',
    ],
  ];
}
