field.widget.settings.link_icon_default:
  type: field.widget.settings.link_default:
  label: 'Link icon widget settings'
  mapping:
    available_link_styles:
      type: sequence
      label: 'Available link styles'
      sequence:
        type: string
        label: 'Link style'
    available_positions:
      type: sequence
      label: 'Available positions'
      sequence:
        type: string
        label: 'Available position'

field.formatter.settings.link_icon:
  type: field.formatter.settings.link

field.storage_settings.ef_string_dropdown:
  type: field.storage_settings.string

field.field_settings.link_icon:
  type: field.field_settings.link