field.widget.settings.link_icon_default:
  type: mapping
  label: 'Link icon widget settings'
  mapping:
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
    placeholder_title:
      type: label
      label: 'Placeholder for link text'
    available_link_styles:
      type: sequence
      label: 'Available link styles'
      sequence:
        type: string
        label: 'Link style'
    available_positions:
      type: sequence
      label: 'Available positions'
      sequence:
        type: string
        label: 'Available position'

