<?php

use Drupal\ef\EmbeddableConfigurationHelper;

function ef_is_well_width_install () {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(EmbeddableConfigurationHelper::class)
    ->addCropToMediaImageForm('well_width_13x9');
}

function ef_is_well_width_uninstall () {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(EmbeddableConfigurationHelper::class)
    ->removeCropFromMediaImageForm('well_width_13x9');
}