<?php

use Drupal\ef_secondary_menu\SecondaryMenuThemeHelper;


/**
 * Implements hook_theme
 *
 * @return array
 */
function ef_secondary_menu_theme() {

  return [
    'ef_secondary_menu' => [
      'variables' => [],
    ]
  ];
}

function template_preprocess_ef_secondary_menu (&$variables) {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(SecondaryMenuThemeHelper::class)
    ->preprocessSecondaryMenu($variables);
}
