<?php

use Drupal\ef_secondary_menu\SecondaryMenuThemeHelper;


/**
 * Implements hook_theme
 *
 * @return array
 */
function ef_secondary_menu_theme() {

  return [
    'ef_secondary_menu' => [
      'variables' => [],
    ],
    'ef_secondary_menu_mobile' => [
      'variables' => [],
    ],
  ];
}

function template_preprocess_ef_secondary_menu (&$variables) {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(SecondaryMenuThemeHelper::class)
    ->preprocessSecondaryMenu($variables);
}

function template_preprocess_ef_secondary_menu_mobile (&$variables) {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(SecondaryMenuThemeHelper::class)
    ->preprocessSecondaryMenuMobile($variables);
}