<?php

/**
 * @file
 * Contains ef_reach_through_content.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_form_FORM_ID_alter() for \Drupal\node\NodeTypeForm.
 *
 * Adds reach-through options to the node type form.
 *
 */
function ef_reach_through_content_form_node_type_form_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\ef_reach_through_content\ReachThroughServiceInterface $reach_through_service */
  $reach_through_service = \Drupal::service('ef.reach_through_service');
  $reach_through_service->alterNodeForm($form, $form_state);
}

/**
 * Implements hook_entity_view().
 */
function ef_reach_through_content_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {

  if ($entity->getEntityType()->id() == 'reach_through') {
    /** @var \Drupal\ef_reach_through_content\ReachThroughServiceInterface $reach_through_service */
    $reach_through_service = \Drupal::service('ef.reach_through_service');

    $reach_through_service->viewReachThroughEntity($build, $entity, $display,$view_mode);
  }
}

/**
 * Implements hook_theme().
 */
function ef_reach_through_content_theme() {
  $theme = [];
  $theme['reach_through'] = [
    'render element' => 'elements',
    'file' => 'reach_through.page.inc',
    'template' => 'reach_through',
  ];
  $theme['reach_through_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'reach_through.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function ef_reach_through_content_form_reach_through_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $is_add_form = strpos($form_id, '_add_form') != FALSE;

  if (!$is_add_form) {
    $form['reach_through_ref']['widget'][0]['target_id']['#attributes']['disabled'] = 'disabled';
  }

  \Drupal::service('ef.reach_through_service')->alterReachThroughAddEditForm($form, $form_state, $form_id);
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function ef_reach_through_content_theme_suggestions_reach_through(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#reach_through'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'reach_through__' . $sanitized_view_mode;
  $suggestions[] = 'reach_through__' . $entity->bundle();
  $suggestions[] = 'reach_through__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'reach_through__' . $entity->id();
  $suggestions[] = 'reach_through__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function ef_reach_through_content_reach_through_presave(EntityInterface $entity) {
  \Drupal::service('ef.reach_through_service')->onPresaveReachThrough($entity);
}
/**
 * Implements hook_entity_insert
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function ef_reach_through_content_node_insert (EntityInterface $entity) {
  if ($entity instanceof NodeInterface) {
    \Drupal::service('ef.reach_through_service')->onInsert($entity);
  }
}

/**
 * Implements hook_entity_update
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function ef_reach_through_content_node_update (EntityInterface $entity) {
  if ($entity instanceof NodeInterface) {
    \Drupal::service('ef.reach_through_service')->onUpdate($entity);
  }
}

/**
 * Implements hook_entity_delete
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function ef_reach_through_content_node_delete (EntityInterface $entity) {
  if ($entity instanceof NodeInterface) {
    \Drupal::service('ef.reach_through_service')->onDelete($entity);
  }
}

/**
 * Implements hook_entity_translation_delete
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function ef_reach_through_content_node_translation_delete (EntityInterface $entity) {
  if ($entity instanceof NodeInterface) {
    \Drupal::service('ef.reach_through_service')->onTranslationDelete($entity);
  }
}

/**
 * Implements hook_ENTITY_TYPE_translation_insert().
 */
function ef_reach_through_content_node_translation_insert(EntityInterface $entity) {
  if ($entity instanceof NodeInterface) {
    \Drupal::service('ef.reach_through_service')->onTranslationInsert($entity);
  }
}