<?php

/**
 * @file
 * Contains ef_reach_through_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for \Drupal\node\NodeTypeForm.
 *
 * Adds reach-through options to the node type form.
 *
 */
function ef_reach_through_content_form_node_type_form_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\ef_reach_through_content\ReachThroughServiceInterface $reach_through_service */
  $reach_through_service = \Drupal::service('ef.reach_through_service');
  $reach_through_service->alterNodeForm($form, $form_state);
}

/**
 * Implements hook_theme().
 */
function ef_reach_through_content_theme() {
  $theme = [];
  $theme['reach_through'] = [
    'render element' => 'elements',
    'file' => 'reach_through.page.inc',
    'template' => 'reach_through',
  ];
  $theme['reach_through_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'reach_through.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function ef_reach_through_content_theme_suggestions_reach_through(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#reach_through'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'reach_through__' . $sanitized_view_mode;
  $suggestions[] = 'reach_through__' . $entity->bundle();
  $suggestions[] = 'reach_through__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'reach_through__' . $entity->id();
  $suggestions[] = 'reach_through__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
