services:
  ef_sitewide_settings.manager:
    class: Drupal\ef_sitewide_settings\SitewideSettingsManager
    arguments: []

  ef_sitewide_settings.route_subscriber:
    class: Drupal\ef_sitewide_settings\Routing\RouteSubscriber
    tags:
      - { name: event_subscriber }

