entity.sitewide_settings.view:
  title: 'View'
  route_name: entity.sitewide_settings.canonical
  base_route: entity.sitewide_settings.canonical

entity.sitewide_settings.edit_form:
  title: 'Edit'
  route_name: entity.sitewide_settings.edit_form
  base_route: entity.sitewide_settings.canonical

entity.sitewide_settings.delete_form:
  title: 'Delete'
  route_name: entity.sitewide_settings.delete_form
  base_route: entity.sitewide_settings.canonical
  weight: 10