administer sitewide settings:
  title: 'Administer site-wide settings'
  restrict access: true

permission_callbacks:
  - Drupal\ef_sitewide_settings\SitewideSettingsPermissions::sitewideSettingsTypePermissions