entity.sitewide_settings_type.collection:
  title: 'Site-wide settings types'
  description: 'Create and manage fields and forms for site-wide settings content.'
  route_name:  entity.sitewide_settings_type.collection
  parent: system.admin_structure
