<?php

use Drupal\ef\EmbeddableConfigurationHelper;

function ef_is_mega_widescreen_install () {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(EmbeddableConfigurationHelper::class)
    ->addCropToMediaImageForm('mega_widescreen_30x9');
}

function ef_is_mega_widescreen_uninstall () {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(EmbeddableConfigurationHelper::class)
    ->removeCropFromMediaImageForm('mega_widescreen_30x9');
}