<?php

use Drupal\ef\EmbeddableConfigurationHelper;

/**
 * Implements hook_modules_installed
 *
 * Makes sure that any new node types added are including in the crisis watch link reference target bundle list
 *
 * @param $modules
 */
function ef_crisis_watch_modules_installed($modules) {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(EmbeddableConfigurationHelper::class)
    ->ensureAllTargetBundlesAreSetOnReferenceField('sitewide_settings', 'crisis_watch', 'field_crisis_watch_link');
}

/**
 * Implements hook_theme
 *
 * @return array
 */
function ef_crisis_watch_theme() {

  return [
    'ef_crisis_watch' => [
      'variables' => [
        'location' => 'header',
      ],
    ],
  ];
}

function template_preprocess_ef_crisis_watch (&$variables) {
  /** @var \Drupal\ef_sitewide_settings\SitewideSettingsManagerInterface $settingsManager */
  $settings_manager = \Drupal::service('ef_sitewide_settings.manager');

  /** @var \Drupal\ef_sitewide_settings\SitewideSettingsInterface $crisis_watch_settings */
  $crisis_watch_settings = $settings_manager->getSitewideSettingsForType('crisis_watch');

  if ($crisis_watch_settings) {
    $crisis_watch_linked_page = $crisis_watch_settings->field_crisis_watch_link->entity;

    if ($crisis_watch_linked_page) {
      $a = 1;
    }
  }

}