<?php

use Drupal\Core\Form\FormStateInterface;

function ef_article_dynamic_content_view_filter_bundle () {
  return 'article';
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Ensure error messages for fields within a fieldgroup are shown
 */
function ef_article_form_node_article_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attributes']['novalidate'] = 'novalidate';
}

function ef_article_preprocess_page__node__article (&$variables) {
  $variables['page']['modifiers'][] = 'with-standard-separator';
}