<?php

use Drupal\ef\EmbeddableConfigurationHelper;

function ef_is_fat_portrait_install () {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(EmbeddableConfigurationHelper::class)
    ->addCropToMediaImageForm('fat_portrait_6x7');
}

function ef_is_fat_portrait_uninstall () {
  \Drupal::classResolver()
    ->getInstanceFromDefinition(EmbeddableConfigurationHelper::class)
    ->removeCropFromMediaImageForm('fat_portrait_6x7');
}
